me_passion_data:
    path:     /annonces-data
    defaults: { _controller: MePassionBundle:Default:annoncesData }

me_passion_categories:
    path:    /categories-data
    defaults: { _controller: MePassionBundle:Default:categoriesData }

me_passion_deposer:
    path:     /deposer-data
    defaults: { _controller: MePassionBundle:Default:submit }

me_passion_modifier:
    path:     /modifier-data
    defaults: { _controller: MePassionBundle:Default:modify }

me_passion_delete:
    path:     /supprimer-data/{id}
    defaults: { _controller: MePassionBundle:Default:delete }

me_passion_reponse:
    path:     /reponse-data
    defaults: { _controller: MePassionBundle:Default:respond }

me_passion_email:
    path:     /email-data
    defaults: { _controller: MePassionBundle:Default:forgottenPassword }

me_passion_confirm:
    path:     /confirmer/{id}/{code}
    defaults: { _controller: MePassionBundle:Default:confirm }

me_passion_homepage:
    path:     /
    defaults: { _controller: MePassionBundle:Default:index }

me_passion_check:
    path:     /verification

me_passion_logout:
    path:     /deconnexion

me_passion_mesannonces:
    path:     /mesannonces
    defaults: { _controller: MePassionBundle:Default:index }

me_passion_monannonces:
    path:     /mesannonces/{id}
    defaults: { _controller: MePassionBundle:Default:index }

me_passion_product:
    path:     /annonce/{id}
    defaults: { _controller: MePassionBundle:Default:index }

me_passion_category:
    path:     /{page}
    defaults: { _controller: MePassionBundle:Default:index }
