parameters:
#    me_passion.example.class: Me\PassionBundle\Example

services:
#    me_passion.example:
#        class: %me_passion.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
