security:
    encoders:
        Me\PassionBundle\Entity\User:
            algorithm: bcrypt

    providers:
        users:
            entity: { class: MePassionBundle:User, property: email }

    firewalls:
        secured_area:
            pattern: ^/
            anonymous: ~
            provider: users
            form_login:
                login_path: me_passion_homepage
                check_path: me_passion_check
                default_target_path: me_passion_mesannonces
            logout:
                path: me_passion_logout
                target: me_passion_homepage

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~

    # add all paths that need to be publicly available
    # followed by pattern for secure pages (cf. vendanges)
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
